CC      = gcc

sources =  $(notdir $(wildcard *.c))
objects =  $(addsuffix .o, $(basename $(sources)))
target  = lecture

CFLAGS  = -O3 -fopenmp
LIBS    = -lm

$(target): $(objects)
	$(CC) $(CFLAGS) $^ -o $@ $(LIBS)

%.o : %.c
	$(CC) $(CFLAGS) -c $< -o $@ $(LIBS)

clean:
	rm $(objects) $(target)
