objects =  lecture05.o arithmetic.o

lecture: $(objects)
	gcc -o lecture $(objects)

lecture05.o: lecture05.c 
	gcc -c lecture05.c

arithmetic.o: arithmetic.c arithmetic.h
	gcc -c arithmetic.c

clean:
	rm lecture $(objects)
